package vault

import (
	"fmt"
	"reflect"
	"strings"

	"github.com/goccy/go-yaml"

	"github.com/Kaikei-e/DocDag/config"
)

// header is the note the generated file opens with. It is prepended as bytes
// rather than attached as a YAML comment: a comment map would have to name a
// path inside the document, and this comment is about the document itself.
const header = "# Generated by `uzushio docdag-config` from internal/vault; do not edit by hand.\n" +
	"# Source: github.com/Kaikei-e/uzushio internal/vault (DocDag v0.4.0 spec preset + uzushio kinds).\n"

// Header returns the two lines the generated docdag.yaml opens with, newline
// terminated. A tool that checks the file for staleness compares whole bytes,
// so the header is part of the artefact rather than decoration around it.
func Header() string { return header }

// Marshal renders a configuration as the bytes of docdag.yaml: the header,
// then the YAML. The output is deterministic — goccy sorts mapping keys and
// writes struct fields in declaration order — so a regenerate-and-diff check
// in CI compares the configuration rather than the whim of a serialiser.
//
// It refuses a configuration Validate rejects, and one carrying a raw tab or
// carriage return in any string: both survive a marshal, and both come back
// from a parser as something other than what went in.
func Marshal(cfg config.Config) ([]byte, error) {
	if err := cfg.Validate(); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrConfig, err)
	}
	if err := checkWhitespace(cfg); err != nil {
		return nil, err
	}
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("%w: marshal: %w", ErrConfig, err)
	}
	return append([]byte(header), body...), nil
}

// Generate assembles the configuration and renders it in one call, which is
// what the CLI and the tests both want.
func Generate() ([]byte, error) {
	cfg, err := Config()
	if err != nil {
		return nil, err
	}
	return Marshal(cfg)
}

// checkWhitespace walks every string a configuration holds — map keys
// included — and refuses a raw tab or carriage return. YAML has no way to
// carry either through a plain scalar, and the corruption is silent: the value
// comes back re-indented or line-ended differently, and a round-trip that was
// supposed to prove the file says what the Go code says stops proving it.
func checkWhitespace(cfg config.Config) error {
	return walkStrings(reflect.ValueOf(cfg), "config", func(path, value string) error {
		if strings.ContainsAny(value, "\t\r") {
			return fmt.Errorf("%w: %s holds a raw tab or carriage return: %q", ErrConfig, path, value)
		}
		return nil
	})
}

func walkStrings(v reflect.Value, path string, visit func(path, value string) error) error {
	switch v.Kind() {
	case reflect.String:
		return visit(path, v.String())
	case reflect.Pointer, reflect.Interface:
		if v.IsNil() {
			return nil
		}
		return walkStrings(v.Elem(), path, visit)
	case reflect.Slice, reflect.Array:
		for i := range v.Len() {
			if err := walkStrings(v.Index(i), fmt.Sprintf("%s[%d]", path, i), visit); err != nil {
				return err
			}
		}
	case reflect.Map:
		for _, key := range v.MapKeys() {
			at := fmt.Sprintf("%s[%v]", path, key)
			if err := walkStrings(key, at+" (key)", visit); err != nil {
				return err
			}
			if err := walkStrings(v.MapIndex(key), at, visit); err != nil {
				return err
			}
		}
	case reflect.Struct:
		for i := range v.NumField() {
			field := v.Type().Field(i)
			if !field.IsExported() {
				continue
			}
			if err := walkStrings(v.Field(i), path+"."+field.Name, visit); err != nil {
				return err
			}
		}
	case reflect.Bool, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr,
		reflect.Float32, reflect.Float64, reflect.Complex64, reflect.Complex128,
		reflect.Chan, reflect.Func, reflect.UnsafePointer, reflect.Invalid:
		// Nothing in a configuration of these kinds carries a string.
	}
	return nil
}
