package vault

import (
	"bytes"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"testing"

	"github.com/Kaikei-e/DocDag/config"
	"github.com/Kaikei-e/DocDag/lint"
	"github.com/Kaikei-e/DocDag/model"

	"github.com/Kaikei-e/uzushio/internal/vocab"
)

func TestHeader(t *testing.T) {
	header := Header()
	if !strings.HasPrefix(header, "# Generated by `uzushio docdag-config`") {
		t.Fatalf("header = %q", header)
	}
	if !strings.HasSuffix(header, "\n") {
		t.Fatal("the header does not end in a newline")
	}
	out, err := Generate()
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !bytes.HasPrefix(out, []byte(header)) {
		t.Fatalf("the generated file does not open with the header:\n%s", out[:min(len(out), 200)])
	}
}

// TestMarshalIsDeterministic is what makes `make check` meaningful: the same
// configuration has to render to the same bytes, or a regenerate-and-diff step
// reports the serialiser rather than the change.
func TestMarshalIsDeterministic(t *testing.T) {
	cfg := mustConfig(t)
	var first []byte
	for i := range 3 {
		out, err := Marshal(cfg)
		if err != nil {
			t.Fatalf("Marshal %d: %v", i, err)
		}
		if i == 0 {
			first = out
			continue
		}
		if !bytes.Equal(first, out) {
			t.Fatalf("Marshal %d differs from the first:\n--- first ---\n%s\n--- again ---\n%s", i, first, out)
		}
	}
	// Reassembling the configuration has to give the same bytes too: nothing
	// in the assembly may depend on map iteration order.
	again, err := Generate()
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !bytes.Equal(first, again) {
		t.Fatal("a freshly assembled configuration renders to different bytes")
	}
}

// TestMarshalRoundTrip holds the generated file to the cycle DocDag holds its
// own presets to: marshal, load, and be the same value. A field the writer
// drops would otherwise leave the file saying less than the Go code does.
func TestMarshalRoundTrip(t *testing.T) {
	cfg := mustConfig(t)
	out, err := Marshal(cfg)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	path := filepath.Join(t.TempDir(), config.DefaultConfigFile)
	if err := os.WriteFile(path, out, 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}
	got, err := config.Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if err := got.Validate(); err != nil {
		t.Fatalf("Validate after Load: %v", err)
	}
	if !reflect.DeepEqual(got, cfg) {
		t.Fatalf("round trip changed the configuration\n--- loaded ---\n%+v\n--- built ---\n%+v", got, cfg)
	}
	// The file is written whole, so merging it onto the preset it names adds
	// nothing: what is on disk is what the engine runs.
	merged := config.Merge(config.SpecPreset(), got)
	if !reflect.DeepEqual(merged, cfg) {
		t.Fatal("merging the generated file onto the spec preset changes it; the file is not self-contained")
	}
}

func TestMarshalRejectsRawWhitespace(t *testing.T) {
	tests := []struct {
		name string
		mut  func(*config.Config)
	}{
		{"a tab in a message", func(cfg *config.Config) { cfg.Rules[0].Message += "\tindented" }},
		{"a carriage return in a message", func(cfg *config.Config) { cfg.Rules[0].Message += "\r\n" }},
		{"a tab in a field vocabulary", func(cfg *config.Config) {
			spec := cfg.Kinds[vocab.KindRun.String()]
			verdict := spec.Fields[vocab.FieldVerdict.String()]
			verdict.OneOf = append(slices.Clone(verdict.OneOf), "a\tb")
			spec.Fields[vocab.FieldVerdict.String()] = verdict
			cfg.Kinds[vocab.KindRun.String()] = spec
		}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := mustConfig(t)
			tt.mut(&cfg)
			if _, err := Marshal(cfg); !errors.Is(err, ErrConfig) {
				t.Fatalf("Marshal error = %v, want ErrConfig", err)
			}
		})
	}
}

func TestMarshalRejectsAnInvalidConfig(t *testing.T) {
	cfg := mustConfig(t)
	spec := cfg.Kinds[vocab.KindRun.String()]
	spec.ID = `^run/(unclosed$`
	cfg.Kinds[vocab.KindRun.String()] = spec
	if _, err := Marshal(cfg); !errors.Is(err, ErrConfig) {
		t.Fatalf("Marshal error = %v, want ErrConfig", err)
	}
}

func errorsOnly(findings []model.Finding) []model.Finding {
	var out []model.Finding
	for _, f := range findings {
		if f.Severity == model.SeverityError {
			out = append(out, f)
		}
	}
	return out
}

// TestLintInherentLayer runs the layer that needs no vault on disk: the DNF
// analysis of the configuration itself. It reports conditions no document
// could satisfy, rules that say what another rule already says, and vocabulary
// nothing reads — the faults of a specification rather than of a corpus.
func TestLintInherentLayer(t *testing.T) {
	cfg := mustConfig(t)
	findings, err := lint.Check(cfg, "", "")
	if err != nil {
		t.Fatalf("lint.Check: %v", err)
	}
	if len(findings) != 0 {
		for _, f := range findings {
			t.Errorf("%s %s %s: %s", f.Severity, f.Rule, f.ID, f.Detail)
		}
		t.Fatalf("the inherent layer reports %d findings, want none", len(findings))
	}
}

// TestLintFixtureLayerWantsOnlyFixtures runs the inherent layer plus the
// fixture layer against an empty fixture directory. Every rule uzushio adds is
// expected to report missing_fixture twice — once for ruleid, once for ok —
// because the fixture corpora are Phase B's work; the preset's own ten rules
// are exempt by name. Nothing else may appear: the assertion is that the only
// warnings are missing_fixture, and that each names a uzushio rule.
func TestLintFixtureLayerWantsOnlyFixtures(t *testing.T) {
	cfg := mustConfig(t)
	findings, err := lint.Check(cfg, "", t.TempDir())
	if err != nil {
		t.Fatalf("lint.Check: %v", err)
	}
	if errs := errorsOnly(findings); len(errs) != 0 {
		for _, f := range errs {
			t.Errorf("%s %s: %s", f.Rule, f.ID, f.Detail)
		}
		t.Fatal("the fixture layer reports errors")
	}
	want := RuleNames()
	counted := map[string]int{}
	for _, f := range findings {
		if f.Rule != "missing_fixture" {
			t.Fatalf("unexpected %s finding %s on %s: %s", f.Severity, f.Rule, f.ID, f.Detail)
		}
		if !slices.Contains(want, f.ID.String()) {
			t.Fatalf("missing_fixture names %q, which is not a uzushio rule", f.ID)
		}
		counted[f.ID.String()]++
	}
	for _, name := range want {
		if counted[name] != 2 {
			t.Fatalf("rule %s got %d missing_fixture findings, want 2", name, counted[name])
		}
	}
}

// TestGeneratedConfigPassesDocdagValidate writes the generated file beside a
// copy of the repository's spec tree and runs the real binary over it. It is
// the end-to-end statement that what this package writes is a configuration
// the released engine accepts, and it is skipped where no docdag is installed.
func TestGeneratedConfigPassesDocdagValidate(t *testing.T) {
	binary, err := exec.LookPath("docdag")
	if err != nil {
		t.Skip("no docdag on PATH; skipping the end-to-end validation")
	}
	out, err := Generate()
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	root := t.TempDir()
	repo, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("locate the repository root: %v", err)
	}
	if err := os.CopyFS(filepath.Join(root, "spec"), os.DirFS(filepath.Join(repo, "spec"))); err != nil {
		t.Fatalf("copy the spec tree: %v", err)
	}
	// The three kinds uzushio adds have no documents yet; their directories
	// exist so the parser reads an empty corpus rather than a missing one.
	for _, k := range vocab.AllKinds() {
		dir, _ := vocab.Dir(k)
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatalf("create %s: %v", dir, err)
		}
	}
	if err := os.WriteFile(filepath.Join(root, config.DefaultConfigFile), out, 0o600); err != nil {
		t.Fatalf("write the configuration: %v", err)
	}
	cmd := exec.CommandContext(t.Context(), binary, "validate")
	cmd.Dir = root
	report, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("docdag validate: %v\n%s", err, report)
	}
	t.Logf("docdag validate:\n%s", report)
}
