// Package proposeedit turns a failure pattern into harness edits a person or a
// run can judge.
//
// It does that by asking the harness to improve itself, in exactly the way the
// harness is asked to do anything else: a CMoA task whose repository is the
// rendered harness directory, whose instruction is the pattern plus the rules a
// harness edit has to obey, and whose answer is a unified diff. Nothing here
// invents a second proposer or a second output contract — the proposers, the
// prompt and the diff extraction are CMoA's, and this package builds the task,
// runs `cmoa propose` over it, and reads what came back into vault documents.
//
// The asymmetry worth naming: a candidate is a diff, and an edit to the memory
// or skill surface is a whole file. That is not a mismatch to paper over. A
// diff against a harness state cannot be replayed "as of a day" — diffs do not
// commute and the vault's periods give them no total order — so an additive
// surface stores the content and only the system-prompt surface, where at most
// one edit is ever in force, keeps a sidecar diff.
package proposeedit

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/Kaikei-e/uzushio/internal/doc"
	"github.com/Kaikei-e/uzushio/internal/surfaces"
)

// ErrPropose is the sentinel every refusal here wraps, so a caller can tell a
// candidate uzushio will not turn into an edit from an I/O failure.
var ErrPropose = fmt.Errorf("proposeedit")

// TaskVersion is the task.json version the generated task declares. Version 2
// is what carries a verify kind; the task is never verified — `cmoa propose`
// does not run the verifier — but a manifest that says which version it is
// written against is one CMoA can keep reading.
const TaskVersion = 2

// composeStub is the compose file the generated task names. CMoA checks that
// the file exists when it loads a task and never runs it during propose, so the
// stub declares the service and nothing else: writing a runnable verifier for a
// task nobody verifies would be a lie about what the task is for.
const composeStub = `# Generated by uzushio improve --propose.
#
# cmoa checks that a task's compose file exists before it will load the task.
# This task is only ever proposed against: its answer is a harness edit, which
# is judged by running the suite with the edit in force, not by a container
# here. The service exists so the manifest is honest about naming one.
services:
  verify:
    image: alpine:3
    command: ["false"]
`

// taskIDPattern is CMoA's task identifier shape, which the generated task's id
// has to satisfy.
var taskIDPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,63}$`)

// slugPart is what a generated identifier's segments may hold.
var slugPart = regexp.MustCompile(`[^a-z0-9]+`)

// TaskDir is a built task: where it is, what its identifier is, and which files
// of the harness it put in front of the proposers.
type TaskDir struct {
	// Dir is the task directory, absolute.
	Dir string
	// ID is the task identifier CMoA will record.
	ID string
	// Files are the harness files the task listed, slash separated and sorted.
	Files []string
}

// BuildTask writes a CMoA task whose repository is a copy of the rendered
// harness directory, into work (which must be empty or absent).
//
// The repository is a git repository with one commit, because CMoA resolves the
// task's revision before it proposes anything and a directory with no history
// has no revision to resolve. The harness is copied rather than used in place:
// a proposer must never be able to reach the caller's rendered tree, and the
// commit is what makes `git apply` on a candidate a check rather than a guess.
func BuildTask(ctx context.Context, harness, work string, pattern doc.Pattern) (*TaskDir, error) {
	id, err := taskIDFor(pattern.PatternID)
	if err != nil {
		return nil, err
	}
	dir, err := filepath.Abs(work)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrPropose, err)
	}
	// The directory is this call's to own. Re-running --propose with the same
	// --out is the ordinary way to retry one, and a half-built task left by the
	// last attempt would make `git commit` fail with "nothing to commit" rather
	// than rebuild.
	if err := os.RemoveAll(dir); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrPropose, err)
	}
	repo := filepath.Join(dir, "repo")
	if err := os.MkdirAll(repo, 0o755); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrPropose, err)
	}
	if err := copyTree(harness, repo); err != nil {
		return nil, err
	}
	// The two directories are part of the contract even when they are empty:
	// they are what tells a proposer where it is allowed to act. A harness that
	// grew its skills/ directory only once a skill existed would be a harness
	// nobody could add the first skill to.
	files, err := ensureSurfaces(repo)
	if err != nil {
		return nil, err
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("%w: the rendered harness at %s holds no files", ErrPropose, harness)
	}
	instruction := Instruction(pattern)
	if err := os.WriteFile(filepath.Join(dir, "instruction.md"), []byte(instruction), 0o644); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrPropose, err)
	}
	if err := os.WriteFile(filepath.Join(dir, "compose.yaml"), []byte(composeStub), 0o644); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrPropose, err)
	}
	budget, err := contextBudget(repo, files, len(instruction))
	if err != nil {
		return nil, err
	}
	manifest := map[string]any{
		"version":           TaskVersion,
		"id":                id,
		"repo":              "repo",
		"rev":               "HEAD",
		"files":             files,
		"max_context_bytes": budget,
		"verify":            map[string]any{"compose_file": "compose.yaml", "service": "verify", "kind": "exit-code"},
	}
	raw, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrPropose, err)
	}
	if err := os.WriteFile(filepath.Join(dir, "task.json"), append(raw, '\n'), 0o644); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrPropose, err)
	}
	if err := initRepo(ctx, repo); err != nil {
		return nil, err
	}
	return &TaskDir{Dir: dir, ID: id, Files: files}, nil
}

// taskIDFor names the generated task after the pattern it is about, so a trace
// left behind says which pattern it came from without anything having to be
// looked up.
func taskIDFor(patternID string) (string, error) {
	slug := strings.Trim(slugPart.ReplaceAllString(strings.ToLower(patternID), "-"), "-")
	id := "improve-" + slug
	if len(id) > 64 {
		// Truncating alone would collide two long pattern identifiers onto one
		// task, and then two proposal rounds would write into one runs/
		// directory and each would look like the other's history. The digest
		// keeps them apart without making the name unreadable.
		sum := sha256.Sum256([]byte(patternID))
		suffix := "-" + hex.EncodeToString(sum[:4])
		id = strings.TrimRight(id[:64-len(suffix)], "-") + suffix
	}
	if !taskIDPattern.MatchString(id) {
		return "", fmt.Errorf("%w: pattern %q gives no usable task id (%q)", ErrPropose, patternID, id)
	}
	return id, nil
}

// contextBudget sizes max_context_bytes to what the task actually holds, with
// room to spare. CMoA's default is a guard against a task that would not fit a
// context window, and a harness that has grown past it is a harness worth
// proposing against rather than a task worth refusing.
func contextBudget(repo string, files []string, instruction int) (int, error) {
	total := instruction
	for _, f := range files {
		info, err := os.Stat(filepath.Join(repo, filepath.FromSlash(f)))
		if err != nil {
			return 0, fmt.Errorf("%w: %w", ErrPropose, err)
		}
		total += int(info.Size())
	}
	const slack = 65536
	return total + slack, nil
}

// ensureSurfaces makes sure memory/ and skills/ exist and lists every file the
// task should put in front of the proposers, sorted and slash separated.
//
// An empty directory cannot be listed in `files:` and cannot be committed, so
// each empty one gets a `.gitkeep`. That is not a workaround: the file is what
// makes the empty surface visible in the listing the proposer reads, which is
// what tells it the surface exists and is empty rather than absent.
func ensureSurfaces(repo string) ([]string, error) {
	for _, dir := range []string{surfaces.MemoryDir, surfaces.SkillsDir} {
		if err := os.MkdirAll(filepath.Join(repo, dir), 0o755); err != nil {
			return nil, fmt.Errorf("%w: %w", ErrPropose, err)
		}
	}
	var files []string
	err := filepath.WalkDir(repo, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		relative, relErr := filepath.Rel(repo, path)
		if relErr != nil {
			return relErr
		}
		relative = filepath.ToSlash(relative)
		if relative == "." {
			return nil
		}
		if d.IsDir() {
			if relative == ".git" {
				return fs.SkipDir
			}
			return nil
		}
		// The renderer's own manifest describes the tree; it is not part of it,
		// and showing it to a proposer would invite an edit to a file no
		// surface owns.
		if relative == "render.json" {
			return nil
		}
		files = append(files, relative)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrPropose, err)
	}
	for _, dir := range []string{surfaces.MemoryDir, surfaces.SkillsDir} {
		if !hasPrefixIn(files, dir+"/") {
			keep := dir + "/.gitkeep"
			if err := os.WriteFile(filepath.Join(repo, filepath.FromSlash(keep)), nil, 0o644); err != nil {
				return nil, fmt.Errorf("%w: %w", ErrPropose, err)
			}
			files = append(files, keep)
		}
	}
	sort.Strings(files)
	return files, nil
}

// hasPrefixIn reports whether any listed file lives under a prefix.
func hasPrefixIn(files []string, prefix string) bool {
	for _, f := range files {
		if strings.HasPrefix(f, prefix) {
			return true
		}
	}
	return false
}

// copyTree copies the rendered harness into the task's repository, leaving out
// anything that is not harness content.
func copyTree(from, to string) error {
	source, err := filepath.Abs(from)
	if err != nil {
		return fmt.Errorf("%w: %w", ErrPropose, err)
	}
	info, err := os.Stat(source)
	if err != nil {
		return fmt.Errorf("%w: %w", ErrPropose, err)
	}
	if !info.IsDir() {
		return fmt.Errorf("%w: %s is not a directory", ErrPropose, source)
	}
	err = filepath.WalkDir(source, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		relative, relErr := filepath.Rel(source, path)
		if relErr != nil {
			return relErr
		}
		relative = filepath.ToSlash(relative)
		if relative == "." {
			return nil
		}
		if d.IsDir() {
			if relative == ".git" {
				return fs.SkipDir
			}
			return os.MkdirAll(filepath.Join(to, filepath.FromSlash(relative)), 0o755)
		}
		if relative == "render.json" {
			return nil
		}
		body, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		return os.WriteFile(filepath.Join(to, filepath.FromSlash(relative)), body, 0o644)
	})
	if err != nil {
		return fmt.Errorf("%w: %w", ErrPropose, err)
	}
	return nil
}

// initRepo makes the copied harness a repository with one commit. The identity
// is the repository's own so that nothing depends on the caller's git
// configuration, and the commit is what a candidate's diff is applied against.
func initRepo(ctx context.Context, repo string) error {
	// An empty template directory is what keeps a caller's init template — and
	// so a pre-commit hook, and so arbitrary code — out of the repository this
	// package creates and commits into.
	template := filepath.Join(filepath.Dir(repo), "git-template")
	if err := os.MkdirAll(template, 0o755); err != nil {
		return fmt.Errorf("%w: %w", ErrPropose, err)
	}
	steps := [][]string{
		{"init", "--quiet", "--initial-branch=main", "--template=" + template},
		{"config", "user.email", "uzushio@invalid"},
		{"config", "user.name", "uzushio"},
		{"config", "commit.gpgsign", "false"},
		{"config", "core.autocrlf", "false"},
		{"config", "core.hooksPath", template},
		{"add", "--all"},
		{"commit", "--quiet", "--no-gpg-sign", "-m", "the rendered harness"},
	}
	for _, args := range steps {
		if _, err := git(ctx, repo, args...); err != nil {
			return err
		}
	}
	return nil
}

// git runs one git command in a directory and returns its standard output.
//
// The environment is built rather than inherited, and that is the whole point
// of the function. An inherited GIT_DIR — every git hook exports one, and so
// does `git rebase --exec` — makes this stage the harness into somebody else's
// repository; GIT_CONFIG_COUNT is read as command-line configuration and is not
// suppressed by nulling the global file; $XDG_CONFIG_HOME/git/attributes is the
// default core.attributesFile whatever the config says, so a `* text=auto
// eol=crlf` there rewrites every file this commits. None of those may reach a
// step whose output is a proposed edit's content.
func git(ctx context.Context, dir string, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = dir
	var out, errOut bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &errOut
	scratch := filepath.Dir(dir)
	cmd.Env = []string{
		"PATH=" + os.Getenv("PATH"),
		"LC_ALL=C",
		"HOME=" + scratch,
		"XDG_CONFIG_HOME=" + filepath.Join(scratch, "xdg"),
		"GIT_CONFIG_GLOBAL=/dev/null",
		"GIT_CONFIG_SYSTEM=/dev/null",
		"GIT_CONFIG_NOSYSTEM=1",
		"GIT_CONFIG_COUNT=0",
		"GIT_ATTR_NOSYSTEM=1",
		"GIT_TERMINAL_PROMPT=0",
		"GIT_OPTIONAL_LOCKS=0",
	}
	if err := cmd.Run(); err != nil {
		// Both streams are reported: `git commit` says "nothing to commit" on
		// stdout and nothing at all on stderr, and an error ending in a bare
		// colon tells the reader nothing about what happened.
		return "", fmt.Errorf("%w: git %s: %w: %s",
			ErrPropose, strings.Join(args, " "), err,
			strings.TrimSpace(strings.TrimSpace(errOut.String())+" "+strings.TrimSpace(out.String())))
	}
	return out.String(), nil
}
